### PR TITLE
:thread:  threads implementation complete

### PR DESCRIPTION
**Pull request by rohitdalvi18**

### CODE REVIEW

**Comment by rohitdalvi18** [comment]
### Threads preview

Screenshot from 2022-10-23 20-03-05

**Comment by TanmayBhosale** [comment]
Hey, the preview doesn't look right. There is some problem
image

You can find the preview of your pr [here](https://open-nova-3au4m9ucb-tanmaybhosale.vercel.app/)

**Comment by rohitdalvi18** [comment]
@TanmayBhosale 
It seems like you're viewing an old deployment.
It was fixed through [this commit](https://github.com/TanmayBhosale/open-nova/pull/24/commits/fe4d93a531a797964fef0e446992a1df287d3691). You can preview the lastest deployment of this PR [here](https://open-nova-jym0dm0u6-tanmaybhosale.vercel.app/).

**Comment by TanmayBhosale** [comment]
Sorry, my bad Rohit! Looks great! Thank you!

**Pull request merged**
